version: '3'

services:
  frontend:
    build: 
      context: frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_EXTERNAL_PORT:?error}:3000"

  # backend:
  #   build:
  #     context: backend
  #   env_file:
  #     - .env
  #
  db:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9090" /minio/mnt/data
    ports:
      - "9000:9000" # API server
      - "9090:9090" # Web console
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
