version: '3'

services:
  frontend:
    build: 
      dockerfile: dev.dockerfile
      context: frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT:?error}:8080"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json

  backend:
    build:
      context: backend
    env_file:
      - .env
    ports:
      - "${BACKEND_EXTERNAL_PORT:?error}:8000"
  
  db:
    image: quay.io/minio/minio:latest
    command: server --console-address ":${DB_CONSOLE_PORT:?error}" /minio/mnt/data
    ports:
      - "${DB_API_EXTERNAL_PORT:?error}:9000" # API server
      - "${DB_CONSOLE_PORT:?error}:${DB_CONSOLE_PORT:?error}" # Web console
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DB_API_EXTERNAL_PORT:?error}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
