version: '3'

services:
  frontend:
    build: 
      context: frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_EXTERNAL_PORT:?error}:3000"

  # backend:
  #   build:
  #     context: backend
  #   env_file:
  #     - .env
  #
  db:
    image: quay.io/minio/minio:latest
    command: server --console-address ":${BACKEND_CONSOLE_PORT:?error}" /minio/mnt/data
    ports:
      - "${BACKEND_API_EXTERNAL_PORT:?error}:9000" # API server
      - "${BACKEND_CONSOLE_PORT:?error}:${BACKEND_CONSOLE_PORT:?error}" # Web console
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_API_EXTERNAL_PORT:?error}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
