services:
  backend:
    container_name: shimmer-backend
    build: ./backend
    ports:
      - "8080:80"
    environment:
      - ARC_DB_HOST=host.docker.internal
      - ARC_FLIGHT=${ARC_FLIGHT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /RAID:/RAID
  frontend:
    container_name: shimmer-frontend
    build: ./frontend
    ports:
      - "80:80"
