services:
  backend:
    container_name: shimmer-backend
    build: ./backend
    ports:
      - "8080:80"
    environment:
      - HADES_TESTING=True
      - ARC_FLIGHT=-1
      - ARC_DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: shimmer-frontend
    build: ./frontend
    ports:
      - "80:80"
  db:
    container_name: shimmer-db
    build: ./schema
    user: postgres
    environment:
      - POSTGRES_DB=imagery
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
